version: '3.8'

services:
  webfinger:
    build: .
    # Ports are not exposed in production - access via reverse proxy only
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - user_conf.env
    restart: always
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/.well-known/webfinger"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  proxy:
    external: true
